replace_list = [
    "よろしくお願いします。- よろしくお願いします。",
    "本日の伊藤忠商事のI-Colleagueについての会議を開始します。よろしくお願いします。- よろしくお願いします。",
    "本日の伊藤忠商事のI-Colleagueについての会議を開始します。よろしくお願いします。",
    "本日の伊藤忠商事のI-Colleagueについての会議を開始します。",
    "伊藤忠商事のI-Colleagueについての会議を開始します。よろしくお願いします。",
    "伊藤忠商事のI-Colleagueについての会議を開始します。",
    "I-Colleagueについての会議を開始します。よろしくお願いします。",
    "I-Colleagueについての会議を開始します。",
    "I-Colleagueについての会議を",
    "本日の伊藤忠商事の会議を開始します。",
    "本日の伊藤忠商事のI-Colleagueについての会議の正確な文字起こしを開始します。",
    "伊藤忠商事のI-Colleagueについての会議の正確な文字起こしを開始します。",
    "本日の伊藤忠商事のI-Colleagueについての",
    "伊藤忠商事のI-Colleagueについての",
    "本日の会議の正確な文字起こしを開始します。",
    "正確な文字起こしを開始します。",

    "Hi everyone. Thank you for joining today.- Let’s get started.",
    "Hi everyone. Thank you for joining today.",

    # 学習データ対策
    "最後までご視聴頂きありがとうございました",
    "最後までご視聴頂き有難う御座いました",
    "最後までご視聴頂き",
    "最後までご視聴頂き有難うございました",
    "本日はご覧いただき"
    "ご視聴頂きありがとうございました",
    "ご視聴ありがとうございました",
    "字幕視聴ありがとうございました",
    "最後までご視聴いただき",
    "最後まで視聴してくださって 本当に",
    "最後まで視聴してくださって",
    "いいね、チャンネル登録、コメントお願いします",
    "今日の映像はここまでです!",
    "次の映像でお会いしましょう!",
    "次の動画でお会いしましょう!",
    "本日はご覧いただき有難う御座いました",
    "次回もお楽しみに",
    "次回をお楽しみに",
    "以上で終わりたいと思います ありがとうございました",
    "次回の動画でお会いしましょう",
    "では、これで終わりたいと思います",
    "では、これで終わりです",
    "以上で終わります ありがとうございました",

    "よろしくお願いします",
    "以上で会見を終了いたします",
    "伊藤忠商事の始めます",
    "本日はご覧いただきありがとうございました",
    "本日の会議を終了します",
    "ご清聴ありがとうございました",
    "よろしくお願いします",
    "本日はご覧いただきありがとうございます",
    "ご覧いただきありがとうございます",
    "ご視聴ありがとうございました",
    "以上で会見を終了します",
    "本当にありがとうございます",
    "本当にありがとうございました",
    "ありがとうございます",
    "ありがとうございました",
    "有難う御座いました",
    "有難うございました",
    "以上で終わりたいと思います",
    "以上で終わりです",
    "会議を開始します",
    "ごめんなさい",
    "本日の伊藤忠商事は終了です",
    "伊藤忠商事のIColleagueの会議を終了します。",
    "伊藤忠商事のI-Colleagueの会議を終了します。",
    "伊藤忠商事の会議を始めます。",
    "伊藤忠商事のI-Colleagueの会議",
    "伊藤忠商事のI-Colleagueの",
    "以上、伊藤忠商事の会議を開催しています。",
    "先ほどの会議の内容をご覧ください。",
    "以上で伊藤忠商事の終了します。",
    "本日の伊藤商事は以上となります。",
    "インタビューを終了します",
    "本日の会議の",
    "内容を読み上げてください",
    "では、始めましょう",
    "では、どうぞ",
    "久しぶりです",
    "全国の会議です",
    "良い1日を!",
    "では、以上で終わります",
    "はい、これで終わりです",
    "では、これで終わります",
    "次回予告",
    "良い一日を!",
    "良い一日を！",
    "良い一日を",
    "ありがとうございました",
    "本日は。",
    "会見を終了します",
    "Thank you.",
    "Thank you",
    "最後まで",
    "次回予告",
    "焦ってした",
    "次のお気に入りのお菓子をお楽しみください",
    "なお、気をつけて大会に参加させていただき、本日は",
    "なお、気をつけて大会に参加させていただき",
    "気をつけて大会に参加させていただき",
    "大会に参加させていただき",
    "帰ろう",
    "おつかれさまでした",
    "お疲れ様でした",
    "しきしわる",
    "これまでの賃費報告はこれで終わりです",
    "これまでの賃費報告はこれで終わりです",
    "気にせず、おやすいなさい",
    "以上です",
    "本日はご覧頂き",
    "コアパウダーを少しずつ加えて混ぜながら",
    "混ぜなが",
    "字幕をオンにしてご覧ください",
    "スイッチオン",
    "まいです",
    "このような状態になります",
    "1日目はこれで終わりです",
    "次の動画でお会いしましょう",
    "次に、私が作ったビジュアルを読み取るために必要なパターンを選択します",
    "次の日、",
    "次の日",
    "私は彼の家に行く予定です",
    "おやすみなさい",
    "アルミホイルを貼り付けます",
    "1日目はこまです!今日の映像はこまです!",
    "次回へつづく!",
    "次回をお楽しみに",
    "次回をお楽しみに！",
    "次回をお楽しみに!",
    "読売新聞社",
    "詳細は読売新聞社ホームページをご覧ください",
    "ホームページをご覧ください",

    "Thanks for watching!",
    "Thank you for watching.",

    # 禁止用語集
    "pornhub",
    "bokki",
    "何カップ",

    # https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/blob/master/en
    "2g1c",
    "2 girls 1 cup",
    "acrotomophilia",
    "alabama hot pocket",
    "alaskan pipeline",
    "anal",
    "anilingus",
    "anus",
    "apeshit",
    "arsehole",
    "ass",
    "asshole",
    "assmunch",
    "auto erotic",
    "autoerotic",
    "babeland",
    "baby batter",
    "baby juice",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "bangbros",
    "bangbus",
    "bareback",
    "barely legal",
    "barenaked",
    "bastard",
    "bastardo",
    "bastinado",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beaver cleaver",
    "beaver lips",
    "beastiality",
    "bestiality",
    "big black",
    "big breasts",
    "big knockers",
    "big tits",
    "bimbos",
    "birdlock",
    "bitch",
    "bitches",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "blowjob",
    "blow job",
    "blow your load",
    "blue waffle",
    "blumpkin",
    "bollocks",
    "bondage",
    "boner",
    "boob",
    "boobs",
    "booty call",
    "brown showers",
    "brunette action",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bung hole",
    "bunghole",
    "busty",
    "butt",
    "buttcheeks",
    "butthole",
    "camel toe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "chocolate rosebuds",
    "cialis",
    "circlejerk",
    "cleveland steamer",
    "clit",
    "clitoris",
    "clover clamps",
    "clusterfuck",
    "cock",
    "cocks",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "coon",
    "coons",
    "creampie",
    "cum",
    "cumming",
    "cumshot",
    "cumshots",
    "cunnilingus",
    "cunt",
    "darkie",
    "date rape",
    "daterape",
    "deep throat",
    "deepthroat",
    "dendrophilia",
    "dick",
    "dildo",
    "dingleberry",
    "dingleberries",
    "dirty pillows",
    "dirty sanchez",
    "doggie style",
    "doggiestyle",
    "doggy style",
    "doggystyle",
    "dog style",
    "dolcett",
    "domination",
    "dominatrix",
    "dommes",
    "donkey punch",
    "double dong",
    "double penetration",
    "dp action",
    "dry hump",
    "dvda",
    "eat my ass",
    "ecchi",
    "ejaculation",
    "erotic",
    "erotism",
    "escort",
    "eunuch",
    "fag",
    "faggot",
    "fecal",
    "felch",
    "fellatio",
    "feltch",
    "female squirting",
    "femdom",
    "figging",
    "fingerbang",
    "fingering",
    "fisting",
    "foot fetish",
    "footjob",
    "frotting",
    "fuck",
    "fuck buttons",
    "fuckin",
    "fucking",
    "fucktards",
    "fudge packer",
    "fudgepacker",
    "futanari",
    "gangbang",
    "gang bang",
    "gay sex",
    "genitals",
    "giant cock",
    "girl on",
    "girl on top",
    "girls gone wild",
    "goatcx",
    "goatse",
    "god damn",
    "gokkun",
    "golden shower",
    "goodpoop",
    "goo girl",
    "goregasm",
    "grope",
    "group sex",
    "g-spot",
    "guro",
    "hand job",
    "handjob",
    "hard core",
    "hardcore",
    "hentai",
    "homoerotic",
    "honkey",
    "hooker",
    "horny",
    "hot carl",
    "hot chick",
    "how to kill",
    "how to murder",
    "huge fat",
    "humping",
    "incest",
    "intercourse",
    "jack off",
    "jail bait",
    "jailbait",
    "jelly donut",
    "jerk off",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "jizz",
    "juggs",
    "kike",
    "kinbaku",
    "kinkster",
    "kinky",
    "knobbing",
    "leather restraint",
    "leather straight jacket",
    "lemon party",
    "livesex",
    "lolita",
    "lovemaking",
    "make me come",
    "male squirting",
    "masturbate",
    "masturbating",
    "masturbation",
    "menage a trois",
    "milf",
    "missionary position",
    "mong",
    "motherfucker",
    "mound of venus",
    "mr hands",
    "muff diver",
    "muffdiving",
    "nambla",
    "nawashi",
    "negro",
    "neonazi",
    "nigga",
    "nigger",
    "nig nog",
    "nimphomania",
    "nipple",
    "nipples",
    "nsfw",
    "nsfw images",
    "nude",
    "nudity",
    "nutten",
    "nympho",
    "nymphomania",
    "octopussy",
    "omorashi",
    "one cup two girls",
    "one guy one jar",
    "orgasm",
    "orgy",
    "paedophile",
    "paki",
    "panties",
    "panty",
    "pedobear",
    "pedophile",
    "pegging",
    "penis",
    "phone sex",
    "piece of shit",
    "pikey",
    "pissing",
    "piss pig",
    "pisspig",
    "playboy",
    "pleasure chest",
    "pole smoker",
    "ponyplay",
    "poof",
    "poon",
    "poontang",
    "punany",
    "poop chute",
    "poopchute",
    "porn",
    "porno",
    "pornography",
    "prince albert piercing",
    "pthc",
    "pubes",
    "pussy",
    "queaf",
    "queef",
    "quim",
    "raghead",
    "raging boner",
    "rape",
    "raping",
    "rapist",
    "rectum",
    "reverse cowgirl",
    "rimjob",
    "rimming",
    "rosy palm",
    "rosy palm and her 5 sisters",
    "rusty trombone",
    "sadism",
    "santorum",
    "scat",
    "schlong",
    "scissoring",
    "semen",
    "sex",
    "sexcam",
    "sexo",
    "sexy",
    "sexual",
    "sexually",
    "sexuality",
    "shaved beaver",
    "shaved pussy",
    "shemale",
    "shibari",
    "shit",
    "shitblimp",
    "shitty",
    "shota",
    "shrimping",
    "skeet",
    "slanteye",
    "slut",
    "s&m",
    "smut",
    "snatch",
    "snowballing",
    "sodomize",
    "sodomy",
    "spastic",
    "spic",
    "splooge",
    "splooge moose",
    "spooge",
    "spread legs",
    "spunk",
    "strap on",
    "strapon",
    "strappado",
    "strip club",
    "style doggy",
    "suck",
    "sucks",
    "suicide girls",
    "sultry women",
    "swastika",
    "swinger",
    "tainted love",
    "taste my",
    "tea bagging",
    "threesome",
    "throating",
    "thumbzilla",
    "tied up",
    "tight white",
    "tit",
    "tits",
    "titties",
    "titty",
    "tongue in a",
    "topless",
    "tosser",
    "towelhead",
    "tranny",
    "tribadism",
    "tub girl",
    "tubgirl",
    "tushy",
    "twat",
    "twink",
    "twinkie",
    "two girls one cup",
    "undressing",
    "upskirt",
    "urethra play",
    "urophilia",
    "vagina",
    "venus mound",
    "viagra",
    "vibrator",
    "violet wand",
    "vorarephilia",
    "voyeur",
    "voyeurweb",
    "voyuer",
    "vulva",
    "wank",
    "wetback",
    "wet dream",
    "white power",
    "whore",
    "worldsex",
    "wrapping men",
    "wrinkled starfish",
    "xx",
    "xxx",
    "yaoi",
    "yellow showers",
    "yiffy",
    "zoophilia",
    "🖕",

    # https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/blob/master/ja
    "3p",
    "g スポット",
    "s ＆ m",
    "sm",
    "sm女王",
    "xx",
    "アジアのかわいい女の子",
    "アスホール",
    "アナリングス",
    "アナル",
    "いたずら",
    "イラマチオ",
    "エクスタシー",
    "エスコート",
    "エッチ",
    "エロティズム",
    "エロティック",
    "オーガズム",
    "オカマ",
    "おしっこ",
    "おしり",
    "オシリ",
    "おしりのあな",
    "おっぱい",
    "オッパイ",
    "オナニー",
    "オマンコ",
    "おもらし",
    "お尻",
    "カーマスートラ",
    "カント",
    "クリトリス",
    "グループ・セックス",
    "グロ",
    "クンニリングス",
    "ゲイ・セックス",
    "ゲイボーイ",
    "ゴールデンシャワー",
    "コカイン",
    "ゴックン",
    "サディズム",
    "しばり",
    "スウィンガー",
    "スカートの中",
    "スカトロ",
    "ストラップオン",
    "ストリップ劇場",
    "スラット",
    "スリット",
    "セクシーな",
    "セクシーな 10 代",
    "セックス",
    "ソドミー",
    "ちんこ",
    "ディープ・スロート",
    "ディック",
    "ディルド",
    "デートレイプ",
    "デブ",
    "テレフォンセックス",
    "ドッグスタイル",
    "トップレス",
    "なめ",
    "ニガー",
    "ヌード",
    "ネオ・ナチ",
    "ハードコア",
    "パイパン",
    "バイブレーター",
    "バック・スタイル",
    "パンティー",
    "ビッチ",
    "ファック",
    "ファンタジー",
    "フィスト",
    "フェティッシュ",
    "フェラチオ",
    "ふたなり",
    "ぶっかけ",
    "フック",
    "プリンス アルバート ピアス",
    "プレイボーイ",
    "ベアバック",
    "ペニス",
    "ペニスバンド",
    "ボーイズラブ",
    "ボールギャグ",
    "ぽっちゃり",
    "ホモ",
    "ポルノ",
    "ポルノグラフィー",
    "ボンテージ",
    "マザー・ファッカー",
    "マスターベーション",
    "まんこ",
    "やおい",
    "やりまん",
    "ラティーナ",
    "ラバー",
    "ランジェリー",
    "レイプ",
    "レズビアン",
    "ローター",
    "ロリータ",
    "淫乱",
    "陰毛",
    "革抑制",
    "騎上位",
    "巨根",
    "巨乳",
    "強姦犯",
    "玉なめ",
    "玉舐め",
    "緊縛",
    "近親相姦",
    "嫌い",
    "後背位",
    "合意の性交",
    "拷問",
    "殺し方",
    "殺人事件",
    "殺人方法",
    "支配",
    "児童性虐待",
    "自己愛性",
    "射精",
    "手コキ",
    "獣姦",
    "女の子",
    "女王様",
    "女子高生",
    "女装",
    "新しいポルノ",
    "人妻",
    "人種",
    "性交",
    "正常位",
    "生殖器",
    "精液",
    "挿入",
    "足フェチ",
    "足を広げる",
    "大陰唇",
    "脱衣",
    "茶色のシャワー",
    "中出し",
    "潮吹き女",
    "潮吹き男性",
    "直腸",
    "剃毛",
    "貞操帯",
    "奴隷",
    "二穴",
    "乳首",
    "尿道プレイ",
    "覗き",
    "売春婦",
    "縛り",
    "噴出",
    "糞",
    "糞尿愛好症",
    "糞便",
    "平手打ち",
    "変態",
    "勃起する",
    "夢精",
    "毛深い",
    "誘惑",
    "幼児性愛者",
    "裸",
    "裸の女性",
    "乱交",
    "両性",
    "両性具有",
    "両刀",
    "輪姦",
    "卍",
    "宦官",
    "肛門",
    "膣",

    # https://tk-blogmaster.com/ng-adsense/
    '穢多',
    'アメ公',
    'ちんば',
    '痴呆症',
    '穢多',
    '坊主',
    '毛唐',
    '支那畜',
    'めくら',
    'びっこ',
    '看護婦',
    '癪病',
    'ホモ',
    '非人',
    '百姓',
    '紅毛人',
    'チョン',
    'つんぼ',
    'かたわ',
    '助産婦',
    '土人',
    'レズ',
    '賎民',
    'お水',
    'クロンボ',
    'ブリカス',
    'おし',
    'きちがい',
    '保母',
    '肌色',
    'オカマ',
    '乞食',
    '汚穢屋',
    'ロスケ',
    'ユダ公',
    'どもり',
    '白痴',
    '伝染病',
    '精神分裂症',
    'バイ',
    '陰核',
    'クンニ',
    '愛液',
    'イメクラ',
    'ディルド',
    '輸姦',
    '外性器',
    'ペニス',
    '性交',
    '手淫',
    '勃起',
    '潮吹き',
    '売春婦',
    'デリヘル',
    'オナホール',
    'ピンロー',
    'ロリコン',
    '青姦',
    '男性器',
    '巨根',
    '体位',
    '手マン',
    '早漏',
    '射精',
    '風俗嬢',
    'ラブホ',
    'ラブドール',
    'バイアグラ',
    'スカトロ',
    '獣姦',
    '女性器',
    'マンコ',
    '騎乗位',
    '手コキ',
    '遅漏',
    '中出し',
    '立ちんぼ',
    'ブルセラ',
    'バイブ',
    'ペニバン',
    '飲尿',
    '屍姦',
    '陰茎',
    'クリトリス',
    'まんぐり返し',
    'フェラチオ',
    'ガマン汁',
    '本気汁',
    'AV女優',
    'ソープランド',
    '電マ',
    '裏ビデオ',
    'アナル',
    '浣腸プレイ'
    'ブス',
    'あほ',
    'ばか',
    '殺人',
    '他殺'
    '自殺',
    '暴力団',
    '強姦'
    '暴行',
    '拳銃',
    '爆弾'
    'ミサイル',
    '覚醒剤',
    'マリファナ',
    'コカイン',
    'チビ',
    '死ね',
    '斬殺',
    '刃傷',
    'ヤクザ',
    '脅迫',
    '機関銃',
    'バズーカ',
    'シャブ',
    'ヘロイン',
    'ジジイ',
    'のるま',
    '刺殺',
    '殺傷',
    'テロ',
    '強盗',
    '手榴弾',
    '長刀',
    'ヤーバー',
    'あへん',
    'ババア',
    'どじ',
    '締殺',
    '傷害',
    '暴力革命',
    '恐喝',
    'バズーカ',
    'ドス',
    '大麻',
    'MDMA',

    "銃声"
]
